import { ArrowDown, ArrowRight, ArrowUp, CheckCircle, Circle, CircleOff, HelpCircle, Timer } from "lucide-react";
import { z } from "zod";

import type { TFunction } from "@/lib/i18n/dictionary";

const taskSchema = z.object({
  id: z.string(),
  title: z.string(),
  status: z.string(),
  label: z.string(),
  priority: z.string(),
});

export type Task = z.infer<typeof taskSchema>;

// 任务标题属于演示内容，直接写中文；`status` / `label` / `priority` 参与筛选与查找，保持英文原值。
const tasksData = [
  {
    id: "TASK-8782",
    title: "不量化开源 SSD 像素，就无法压缩这个程序！",
    status: "in progress",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-7878",
    title: "试试计算 EXE 数据源，也许它能索引多字节像素！",
    status: "backlog",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-7839",
    title: "我们需要绕过神经网络 TCP 网卡！",
    status: "todo",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-5562",
    title: "SAS 接口挂了，绕过开源像素以便备份 PNG 带宽！",
    status: "backlog",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-8686",
    title: "我来解析无线 SSL 协议，这样应该能驱动 API 面板！",
    status: "canceled",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-1280",
    title: "使用数字 TLS 面板，然后就能传输触觉系统！",
    status: "done",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-7262",
    title: "UTF8 应用挂了，解析神经带宽以便备份 PNG 防火墙！",
    status: "done",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-1138",
    title: "生成驱动程序没用，我们需要量化 1080p SMTP 带宽！",
    status: "in progress",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-7184",
    title: "我们需要给后端 THX 像素编程！",
    status: "todo",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-5160",
    title: "计算总线没用，我们需要导航后端 JSON 协议！",
    status: "in progress",
    label: "documentation",
    priority: "high",
  },
  {
    id: "TASK-5618",
    title: "生成驱动程序没用，我们需要索引在线 SSL 应用！",
    status: "done",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-6699",
    title: "我来传输无线 JBOD 电容，这样应该能驱动 SSD 数据源！",
    status: "backlog",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-2858",
    title: "我们需要覆盖在线 UDP 总线！",
    status: "backlog",
    label: "bug",
    priority: "medium",
  },
  {
    id: "TASK-9864",
    title: "我来重启 1080p FTP 面板，这样应该能矩阵化 HEX 硬盘！",
    status: "done",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-8404",
    title: "我们需要生成虚拟 HEX 警报！",
    status: "in progress",
    label: "bug",
    priority: "low",
  },
  {
    id: "TASK-5365",
    title: "备份像素没用，我们需要传输主 IB 阵列！",
    status: "in progress",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-1780",
    title: "CSS 数据源挂了，索引蓝牙发射器以便压缩 CLI 协议！",
    status: "todo",
    label: "documentation",
    priority: "high",
  },
  {
    id: "TASK-6938",
    title: "使用冗余 SCSI 应用，然后就能破解光纤警报！",
    status: "todo",
    label: "documentation",
    priority: "high",
  },
  {
    id: "TASK-9885",
    title: "我们需要压缩辅助 VGA 驱动！",
    status: "backlog",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-3216",
    title: "传输发射器没用，我们需要压缩虚拟 HDD 传感器！",
    status: "backlog",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-9285",
    title: "IP 监视器挂了，复制触觉警报以便生成 HTTP 发射器！",
    status: "todo",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-1024",
    title: "覆盖微芯片没用，我们需要传输数字 OCR 发射器！",
    status: "in progress",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-7068",
    title: "不索引无线 HEX 像素，就无法生成电容！",
    status: "canceled",
    label: "bug",
    priority: "low",
  },
  {
    id: "TASK-6502",
    title: "导航微芯片没用，我们需要绕过后端 SQL 总线！",
    status: "todo",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-5326",
    title: "我们需要破解冗余 UTF8 发射器！",
    status: "todo",
    label: "bug",
    priority: "low",
  },
  {
    id: "TASK-6274",
    title: "使用虚拟 PCI 电路，然后就能解析蓝牙警报！",
    status: "canceled",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-1571",
    title: "我来输入神经 DRAM 电路，这样应该就能协议化 SMTP 接口！",
    status: "in progress",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-9518",
    title: "压缩接口没用，我们需要压缩在线 SDD 矩阵！",
    status: "canceled",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-5581",
    title: "我来合成数字 COM 像素，这样应该能发射 UTF8 协议！",
    status: "backlog",
    label: "documentation",
    priority: "high",
  },
  {
    id: "TASK-2197",
    title: "解析数据源没用，我们需要复制蓝牙 DRAM 总线！",
    status: "todo",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-8484",
    title: "我们需要解析固态 UDP 防火墙！",
    status: "in progress",
    label: "bug",
    priority: "low",
  },
  {
    id: "TASK-9892",
    title: "如果我们备份这个应用，就能通过多字节 THX 电容访问 UDP 应用！",
    status: "done",
    label: "documentation",
    priority: "high",
  },
  {
    id: "TASK-9616",
    title: "我们需要合成跨平台 ASCII 像素！",
    status: "in progress",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-9744",
    title: "使用后端 IP 网卡，然后就能输入固态硬盘！",
    status: "done",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-1376",
    title: "生成警报没用，我们需要生成移动 IP 电容！",
    status: "backlog",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-7382",
    title: "如果我们备份防火墙，就能通过主 UTF8 像素访问 RAM 警报！",
    status: "todo",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-2290",
    title: "我来压缩虚拟 JSON 面板，这样应该能让 UTF8 总线跑起来！",
    status: "canceled",
    label: "documentation",
    priority: "high",
  },
  {
    id: "TASK-1533",
    title: "不覆盖无线 TCP 防火墙，就无法输入防火墙！",
    status: "done",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-4920",
    title: "绕过硬盘没用，我们需要输入蓝牙 JSON 程序！",
    status: "in progress",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-5168",
    title: "如果我们合成总线，就能通过虚拟 TLS 阵列访问 IP 面板！",
    status: "in progress",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-7103",
    title: "我们需要解析多字节 EXE 带宽！",
    status: "canceled",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-4314",
    title: "如果我们压缩这个程序，就能通过多字节 COM 矩阵访问 XML 警报！",
    status: "in progress",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-3415",
    title: "使用跨平台 XML 应用，然后就能量化固态数据源！",
    status: "todo",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-8339",
    title: "试试计算 DNS 接口，也许它会输入蓝牙电容！",
    status: "in progress",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-6995",
    title: "试试破解 XSS 带宽，也许它会覆盖蓝牙矩阵！",
    status: "todo",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-8053",
    title: "如果我们连接这个程序，就能通过数字 UDP 协议访问 UTF8 矩阵！",
    status: "todo",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-4336",
    title: "如果我们合成微芯片，就能通过光纤 UDP 程序访问 SAS 传感器！",
    status: "todo",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-8790",
    title: "我来备份光纤 COM 警报，这样应该能触发 RSS 电容警报！",
    status: "done",
    label: "bug",
    priority: "medium",
  },
  {
    id: "TASK-8980",
    title: "试试导航 SQL 发射器，也许它会备份虚拟防火墙！",
    status: "canceled",
    label: "bug",
    priority: "low",
  },
  {
    id: "TASK-7342",
    title: "使用神经 CLI 网卡，然后就能解析在线端口！",
    status: "backlog",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-5608",
    title: "我来破解触觉 SSL 程序，这样应该能让 UDP 发射器接入总线！",
    status: "canceled",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-1606",
    title: "我来生成蓝牙 PNG 防火墙，这样应该能像素化 SSL 驱动！",
    status: "done",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-7872",
    title: "传输电路没用，我们需要重启 1080p RSS 监视器！",
    status: "canceled",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-4167",
    title: "使用跨平台 SMS 电路，然后就能合成光纤数据源！",
    status: "canceled",
    label: "bug",
    priority: "medium",
  },
  {
    id: "TASK-9581",
    title: "不破解跨平台 XSS 监视器，就无法索引端口！",
    status: "backlog",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-8806",
    title: "我们需要绕过后端 SSL 面板！",
    status: "done",
    label: "bug",
    priority: "medium",
  },
  {
    id: "TASK-6542",
    title: "试试量化 RSS 防火墙，也许它会量化开源系统！",
    status: "done",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-6806",
    title: "VGA 协议挂了，重启后端矩阵以便解析 CSS 面板！",
    status: "canceled",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-9549",
    title: "不连接神经 JBOD 总线，就无法绕过总线！",
    status: "todo",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-1075",
    title: "备份驱动没用，我们需要解析冗余 RAM 像素！",
    status: "done",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-1427",
    title: "使用辅助 PCI 电路，然后就能计算跨平台接口！",
    status: "done",
    label: "documentation",
    priority: "high",
  },
  {
    id: "TASK-1907",
    title: "破解电路没用，我们需要备份在线 DRAM 系统！",
    status: "todo",
    label: "documentation",
    priority: "high",
  },
  {
    id: "TASK-4309",
    title: "如果我们生成这个系统，就能通过光纤 GB 像素访问 TCP 传感器！",
    status: "backlog",
    label: "bug",
    priority: "medium",
  },
  {
    id: "TASK-3973",
    title: "我来解析后端 ADP 阵列，这样应该能拉满 RSS 带宽！",
    status: "todo",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-7962",
    title: "使用无线 RAM 程序，然后就能破解跨平台数据源！",
    status: "canceled",
    label: "bug",
    priority: "low",
  },
  {
    id: "TASK-3360",
    title: "不合成神经 OCR 接口，就无法量化这个程序！",
    status: "done",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-9887",
    title: "使用辅助 ASCII 传感器，然后就能连接固态端口！",
    status: "backlog",
    label: "bug",
    priority: "medium",
  },
  {
    id: "TASK-3649",
    title: "我来输入虚拟 USB 系统，这样应该能让 DNS 监视器形成回路！",
    status: "in progress",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-3586",
    title: "如果我们量化电路，就能通过移动 SMS 硬盘访问 CLI 数据源！",
    status: "in progress",
    label: "bug",
    priority: "low",
  },
  {
    id: "TASK-5150",
    title: "我来破解无线 XSS 端口，这样应该能发射 IP 接口！",
    status: "canceled",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-3652",
    title: "SQL 接口挂了，覆盖光纤总线以便给 ASCII 接口编程！",
    status: "backlog",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-6884",
    title: "使用数字 PCI 电路，然后就能合成多字节微芯片！",
    status: "canceled",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-1591",
    title: "我们需要连接移动 XSS 驱动！",
    status: "in progress",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-3802",
    title: "试试覆盖 ASCII 协议，也许它会解析虚拟矩阵！",
    status: "in progress",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-7253",
    title: "给电容编程没用，我们需要绕过神经 IB 硬盘！",
    status: "backlog",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-9739",
    title: "我们需要破解多字节 HDD 总线！",
    status: "done",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-4424",
    title: "试试破解 HEX 警报，也许它会连接光纤像素！",
    status: "in progress",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-3922",
    title: "不生成无线 PCI 程序，就无法备份电容！",
    status: "backlog",
    label: "bug",
    priority: "low",
  },
  {
    id: "TASK-4921",
    title: "我来索引开源 IP 数据源，这样应该能系统化 GB 应用！",
    status: "canceled",
    label: "bug",
    priority: "low",
  },
  {
    id: "TASK-5814",
    title: "我们需要计算 1080p AGP 数据源！",
    status: "backlog",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-2645",
    title: "合成系统没用，我们需要导航多字节 HDD 防火墙！",
    status: "todo",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-4535",
    title: "试试复制 JSON 电路，也许它会连接无线数据源！",
    status: "in progress",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-4463",
    title: "我们需要复制固态 AGP 监视器！",
    status: "done",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-9745",
    title: "如果我们连接协议，就能通过蓝牙 PCI 微芯片访问 GB 系统！",
    status: "canceled",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-2080",
    title: "如果我们输入总线，就能通过辅助 RAM 卡访问 RAM 矩阵！",
    status: "todo",
    label: "bug",
    priority: "medium",
  },
  {
    id: "TASK-3838",
    title: "我来绕过在线 TCP 应用，这样应该能面板化 AGP 系统！",
    status: "backlog",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-1340",
    title: "我们需要导航虚拟 PNG 电路！",
    status: "todo",
    label: "bug",
    priority: "medium",
  },
  {
    id: "TASK-6665",
    title: "如果我们解析监视器，就能通过跨平台 AGP 警报访问 SSD 硬盘！",
    status: "canceled",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-7585",
    title: "如果我们计算硬盘，就能通过多字节 CSS 微芯片访问 SSL 程序！",
    status: "backlog",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-6319",
    title: "我们需要复制多字节 SCSI 程序！",
    status: "backlog",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-4369",
    title: "试试输入 SCSI 总线，也许它会生成 1080p 像素！",
    status: "backlog",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-9035",
    title: "我们需要覆盖固态 PNG 阵列！",
    status: "canceled",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-3970",
    title: "不量化触觉 ASCII 卡，就无法索引发射器！",
    status: "todo",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-4473",
    title: "不覆盖神经 RSS 程序，就无法绕过协议！",
    status: "todo",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-4136",
    title: "不破解主 JSON 程序，就无法破解硬盘！",
    status: "canceled",
    label: "bug",
    priority: "medium",
  },
  {
    id: "TASK-3939",
    title: "使用后端 SQL 防火墙，然后就能连接神经硬盘！",
    status: "done",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-2007",
    title: "我来输入后端 USB 协议，这样应该能拉满 PCI 系统带宽！",
    status: "backlog",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-7516",
    title: "使用主 SQL 程序，然后就能生成辅助发射器！",
    status: "done",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-6906",
    title: "试试备份 DRAM 系统，也许它会重启在线发射器！",
    status: "done",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-5207",
    title: "SMS 接口挂了，复制蓝牙总线以便量化 VGA 显卡！",
    status: "in progress",
    label: "bug",
    priority: "low",
  },
];

export const tasks = z.array(taskSchema).parse(tasksData);

/**
 * 筛选项与单元格标签：`value` 必须与数据里的英文值一致（筛选逻辑依赖它），
 * 只把 `label`（显示给用户的那部分）本地化 —— 所以这些列表改成了接收 t 的函数。
 */
export const labels = (t: TFunction) => [
  {
    value: "bug",
    label: t("common.enums.taskLabel.bug"),
  },
  {
    value: "feature",
    label: t("common.enums.taskLabel.feature"),
  },
  {
    value: "documentation",
    label: t("common.enums.taskLabel.documentation"),
  },
];

export const statuses = (t: TFunction) => [
  {
    value: "backlog",
    label: t("common.enums.taskStatus.backlog"),
    icon: HelpCircle,
  },
  {
    value: "todo",
    label: t("common.enums.taskStatus.todo"),
    icon: Circle,
  },
  {
    value: "in progress",
    label: t("common.enums.taskStatus.in progress"),
    icon: Timer,
  },
  {
    value: "done",
    label: t("common.enums.taskStatus.done"),
    icon: CheckCircle,
  },
  {
    value: "canceled",
    label: t("common.enums.taskStatus.canceled"),
    icon: CircleOff,
  },
];

export const priorities = (t: TFunction) => [
  {
    label: t("common.enums.taskPriority.Low"),
    value: "low",
    icon: ArrowDown,
  },
  {
    label: t("common.enums.taskPriority.Medium"),
    value: "medium",
    icon: ArrowRight,
  },
  {
    label: t("common.enums.taskPriority.High"),
    value: "high",
    icon: ArrowUp,
  },
];
